-- =============================================================================
-- Customer Shopping Behavior Analysis
-- Tech Stack: T-SQL / MS SQL Server
-- Description: End-to-end exploratory and advanced business analysis covering 
--              customer segmentation, revenue drivers, inventory matrix, 
--              and vendor quality control.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. DEMOGRAPHICS & CUSTOMER SEGMENTATION
-- -----------------------------------------------------------------------------

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    gender,
    SUM(purchase_amount) AS total_revenue
FROM dbo.customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id, 
    purchase_amount 
FROM dbo.customer
WHERE discount_applied = 'Yes' 
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM dbo.customer);

-- Q3. Segment customers into New, Returning, and Loyal based on previous purchases.
WITH customer_type AS (
    SELECT 
        customer_id, 
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM dbo.customer
)
SELECT 
    customer_segment,
    COUNT(*) AS total_customers 
FROM customer_type 
GROUP BY customer_segment
ORDER BY total_customers DESC;

-- Q4. What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM dbo.customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q5. Which category and item are most popular within each age group?
WITH AgeGroups AS (
    SELECT 
        age_group,
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (PARTITION BY age_group ORDER BY COUNT(*) DESC) AS rnk
    FROM dbo.customer
    GROUP BY age_group, category, item_purchased
)
SELECT 
    age_group, 
    category, 
    item_purchased, 
    purchase_count
FROM AgeGroups
WHERE rnk = 1;

-- -----------------------------------------------------------------------------
-- 2. REVENUE DRIVERS & DISCOUNT EFFECTIVENESS
-- -----------------------------------------------------------------------------

-- Q6. Compare average purchase amount and revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers, 
    SUM(purchase_amount) AS total_revenue, 
    AVG(purchase_amount) AS avg_spend  
FROM dbo.customer
GROUP BY subscription_status 
ORDER BY total_revenue DESC;

-- Q7. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 
    item_purchased,
    ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate_pct
FROM dbo.customer
GROUP BY item_purchased
ORDER BY discount_rate_pct DESC;

-- Q8. Does applying a discount significantly increase item count or purchase volume?
SELECT 
    discount_applied, 
    COUNT(item_purchased) AS total_items_purchased, 
    SUM(purchase_amount) AS total_revenue, 
    AVG(purchase_amount) AS avg_purchase_amount 
FROM dbo.customer
GROUP BY discount_applied;

-- Q9. Do high-repeat buyers (>5 purchases) show higher subscription adoption?
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM dbo.customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- -----------------------------------------------------------------------------
-- 3. PRODUCT & CATEGORY PERFORMANCE
-- -----------------------------------------------------------------------------

-- Q10. What are the top 5 products with the highest average review rating?
SELECT TOP 5 
    item_purchased, 
    AVG(review_rating) AS avg_item_rating
FROM dbo.customer
GROUP BY item_purchased
HAVING AVG(review_rating) > (SELECT AVG(review_rating) FROM dbo.customer)
ORDER BY avg_item_rating DESC;

-- Q11. Top 3 most purchased products within each category.
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM dbo.customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category, 
    item_purchased, 
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q12. Total revenue and average review rating across product categories.
SELECT 
    category, 
    SUM(purchase_amount) AS total_revenue, 
    AVG(review_rating) AS avg_review_rating 
FROM dbo.customer
GROUP BY category
ORDER BY total_revenue DESC;

-- -----------------------------------------------------------------------------
-- 4. SHIPPING, PAYMENT & GEOGRAPHIC ANALYSIS
-- -----------------------------------------------------------------------------

-- Q13. Compare average purchase amount between Standard and Express shipping.
SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_purchase_amt 
FROM dbo.customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q14. Payment method preferences and average transaction spend by gender.
SELECT 
    gender, 
    payment_method, 
    COUNT(*) AS usage_count,
    AVG(purchase_amount) AS avg_spending
FROM dbo.customer
GROUP BY gender, payment_method
ORDER BY gender, usage_count DESC;

-- Q15. Most popular shipping type and average spend by location.
WITH LocationShipping AS (
    SELECT 
        location,
        shipping_type,
        COUNT(*) AS shipping_count,
        AVG(purchase_amount) AS avg_purchase_amount,
        ROW_NUMBER() OVER (PARTITION BY location ORDER BY COUNT(*) DESC) AS rnk
    FROM dbo.customer
    GROUP BY location, shipping_type
)
SELECT 
    location, 
    shipping_type, 
    shipping_count, 
    avg_purchase_amount
FROM LocationShipping
WHERE rnk = 1;

-- Q16. Seasonal Geography: Top revenue-generating locations in Winter vs. Summer.
WITH SeasonalRevenue AS (
    SELECT 
        season,
        location,
        SUM(purchase_amount) AS total_revenue,
        ROW_NUMBER() OVER (PARTITION BY season ORDER BY SUM(purchase_amount) DESC) AS rnk
    FROM dbo.customer
    WHERE season IN ('Winter', 'Summer')
    GROUP BY season, location
)
SELECT 
    season, 
    location, 
    total_revenue
FROM SeasonalRevenue
WHERE rnk = 1;

-- Q17. Purchase frequency vs. preferred payment methods.
SELECT 
    frequency_of_purchases,
    payment_method,
    COUNT(*) AS total_orders
FROM dbo.customer
GROUP BY frequency_of_purchases, payment_method
ORDER BY frequency_of_purchases, total_orders DESC;

-- -----------------------------------------------------------------------------
-- 5. ADVANCED OPERATIONAL INVENTORY & VENDOR QUALITY
-- -----------------------------------------------------------------------------

-- Q18. Vendor Quality Audit: Identify item and color variants with rating < 3.5.
SELECT 
    item_purchased,
    color,
    AVG(review_rating) AS avg_rating,
    COUNT(*) AS total_sold
FROM dbo.customer
GROUP BY item_purchased, color
HAVING AVG(review_rating) < 3.5
ORDER BY avg_rating ASC;

-- Q19. Size-Color SKU Matrix: Top 5 size-color variants in Clothing for warehouse planning.
SELECT TOP 5 
    size, 
    color, 
    COUNT(*) AS total_purchased
FROM dbo.customer
WHERE category = 'Clothing'
GROUP BY color, size
ORDER BY total_purchased DESC;